### ISSUE TITLE
Author's Issue: Please delete this repository.

### ISSUE THREAD

**Issue by Stereoarts** [MemeHoovy/Sizebox-decompiled#1]
I don't permit to upload my works(codes, images, models, motions, and documents) to public space. Please delete this repository.

**Comment by MemeHoovy** [comment]
how do I know your the owner of this?

**Comment by Stereoarts** [comment]
This file is my works.
https://github.com/MemeHoovy/Sizebox-decompiled/blob/main/Sizebox/AuxiliaryFiles/GameAssemblies/MMD4MecanimInternal.dll

**Comment by Stereoarts** [comment]
Did you check readme_en.txt in MMD4Mecanim?

**Comment by MemeHoovy** [comment]
> Did you check readme_en.txt in MMD4Mecanim?

where?

**Comment by MemeHoovy** [comment]
if you can't prove anything then I ain't deleting shit

**Comment by Stereoarts** [comment]
Dear MemeHoovy,

Thanks for the quick response.
I understand your point of view.

So far I have worked hard for developers.
But I was tired.
I can't support them any more.

**Comment by MemeHoovy** [comment]
lying bitch
